# This is a basic workflow to help you get started with Actions

name: Sync to Gitee

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push, delete, create ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:ValenW/fed-e-task-02-01.git"
          destination-repo: "git@gitee.com:Valen/fed-e-task-02-01.git"  
